# Generated by Django 5.2.3 on 2025-06-11 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='номер номера')),
                ('room_type', models.CharField(max_length=50, verbose_name='тип комнаты')),
                ('price_per_nigt', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='цена за ночь')),
                ('capacity', models.PositiveBigIntegerField(verbose_name='вместимость')),
                ('descripton', models.TextField(blank=True, verbose_name='описание')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='дата заезда')),
                ('check_out_date', models.DateField(verbose_name='дата выезда')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='общая стоимость')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='статус')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room', verbose_name='номер')),
            ],
        ),
    ]
