# Generated by Django 5.2.3 on 2025-07-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price_per_nigt',
            new_name='price_per_night',
        ),
    ]
