# Generated by Django 5.2.3 on 2025-06-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_roomphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default=None, max_length=20, verbose_name='название'),
        ),
    ]
